clone:
  path: github.com/drone-plugins

build:
  image: armhfbuild/golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=arm
    - CGO_ENABLED=0
  commands:
    - apt-get update && apt-get -y install patch
    - git clone --single-branch https://github.com/drone-plugins/drone-docker drone-docker
    - cd drone-docker
    - patch -p1 <../armhf.patch
    - go get
    - go build
    - go test

publish:
  docker: &publish_docker
    context: drone-docker
    file: drone-docker/Dockerfile
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfplugins/drone-docker
    storage_driver: overlay
    when:
      repo: armhf-drone-plugins/drone-docker
      branch: master
  docker:
    <<: *publish_docker
    tag: $$BRANCH
    when:
      repo: armhf-drone-plugins/drone-docker

plugin:
  name: Docker
  desc: Build and Publish images to a Docker registry.
  type: publish
  image: armhfplugins/drone-docker
  labels:
    - docker
    - image
    - container
