clone:
  path: github.com/drone-plugins
  recursive: true

build:
  image: armhfbuild/alpine:3.2
  commands:
    - cd drone-docker
    - patch -p1 <../armhf.patch

build:
  image: armhfbuild/golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=arm
    - CGO_ENABLED=0
  commands:
    - cd drone-docker
    - go get
    - go build
    - go test

publish:
  docker:
    context: drone-docker
    file: drone-docker/Dockerfile
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfplugins/drone-docker
    storage_driver: overlay
    when:
      repo: armhf-drone-plugins/drone-docker
      branch: master

plugin:
  name: Docker
  desc: Build and Publish images to a Docker registry.
  type: publish
  image: armhfplugins/drone-docker
  labels:
    - docker
    - image
    - container
